#!/usr/bin/env bash

awx_user=
awx_password=
awx_host=
ip=$1

function start_awx_job {
    curl -k -s --user $awx_user:$awx_password \
    -X POST -H "Content-Type: application/json" "http://$awx_host/api/v2/workflow_job_templates/12/launch/" \
    --data '{"extra_vars": {"ip_addr":"'$1'"}}'
}

function show_usage {
    cat<<EOF
    Ошибка: указан некорректный IP-адрес 

    Примеры использования:
    addoperator 78.78.78.78
    addoperator 87.87.87.0/24
EOF
    exit 1
}

if [[ $ip ]];then
    if [[ $ip =~ ^((1?[0-9][0-9]?|2[0-4][0-9]|25[0-5])\.){3}(1?[0-9][0-9]?|2[0-4][0-9]|25[0-5])(\/([1-2]?[0-9]|3[0-2]))?$ ]]; then
        job_url=$(start_awx_job $ip | jq .url | tr -d '"')
        job_status=""
        echo "Статус выполнения:"
        while [[ $job_status != *"successful"* ]];
        do
        job_status=$(curl -k -s --user $awx_user:$awx_password -X GET -H "Content-Type: application/json" "http://$awx_host$job_url" | jq .status)
        echo $(date +%H:%M:%S) $job_status
        sleep 3
        done;   
    else
        show_usage
    fi
else
    show_usage
fi

